import type { BiomeType } from "./schemas/enums";

export const GAME_CONSTANTS = {
  ROOMS_PER_FLOOR: 10,
  BOSS_ROOM_INDEX: 9,
  MAX_ALLIES: 3,
  MAX_USABLE_ITEMS: 3,
  MAX_ENEMIES: 4,
  MAX_FLOORS: 5,
  AVAILABLE_BIOMES: [
    "VIKING",
    "GREEK",
    "EGYPTIAN",
    "LOVECRAFTIAN",
    "AZTEC",
    "CELTIC",
    "RUSSIAN",
    "AFRICAN",
  ] as BiomeType[],

  STARTING_HP: 60,
  STARTING_ENERGY: 3,
  STARTING_INK_MAX: 5,
  STARTING_INK_PER_CARD_CHANCE: 0,
  STARTING_INK_PER_CARD_VALUE: 1,
  STARTING_DRAW_COUNT: 4,
  STARTING_GOLD: 0,

  CARD_REWARD_CHOICES: 3,
  ROOM_CHOICES: 3,

  INK_MARK_COST_DEFAULT: 2,

  INK_POWER_COSTS: {
    REWRITE: 3,
    LOST_CHAPTER: 2,
    SEAL: 2,
  },
  SEAL_BLOCK_AMOUNT: 8,
  LOST_CHAPTER_DRAW: 2,

  GOLD_REWARD_BASE: 10,
  GOLD_REWARD_VARIANCE: 6,
  GOLD_PER_EXTRA_ENEMY: 5,
  ELITE_GOLD_BONUS: 18,
  BOSS_GOLD_MULTIPLIER: 2,

  HEAL_ROOM_PERCENT: 0.3,
} as const;
