import type { BiomeType } from "./schemas/enums";

export const GAME_CONSTANTS = {
  ROOMS_PER_FLOOR: 16,
  BOSS_ROOM_INDEX: 15,
  MAP_LANES: 5,
  MAX_ALLIES: 3,
  MAX_USABLE_ITEMS: 3,
  MAX_ENEMIES: 4,
  MAX_HAND_SIZE: 13,
  MAX_FLOORS: 3,
  ALL_BIOMES: [
    "LIBRARY",
    "VIKING",
    "GREEK",
    "EGYPTIAN",
    "LOVECRAFTIAN",
    "AZTEC",
    "CELTIC",
    "RUSSIAN",
    "AFRICAN",
  ] as BiomeType[],
  AVAILABLE_BIOMES: [
    "VIKING",
    "GREEK",
    "EGYPTIAN",
    "LOVECRAFTIAN",
    "AZTEC",
    "CELTIC",
    "RUSSIAN",
    "AFRICAN",
  ] as BiomeType[],

  STARTING_HP: 60,
  STARTING_ENERGY: 3,
  STARTING_INK_MAX: 5,
  STARTING_INK_PER_CARD_CHANCE: 0,
  STARTING_INK_PER_CARD_VALUE: 1,
  STARTING_DRAW_COUNT: 4,
  STARTING_GOLD: 0,

  CARD_REWARD_CHOICES: 3,
  ROOM_CHOICES: 3,

  INK_MARK_COST_DEFAULT: 2,

  INK_POWER_COSTS: {
    // Scribe
    CALLIGRAPHIE: 3,
    ENCRE_NOIRE: 4,
    SEAL: 2,
    // Bibliothécaire
    VISION: 2,
    INDEX: 3,
    SILENCE: 7,
    // Griot
    VENIN: 2,
    SAIGNEMENT: 2,
    GRISGRIS: 2,
    // Fou
    DOUBLE_MISE: 1,
    PACTE_SANG: 0,
    FRENETIQUE: 2,
    // Legacy
    REWRITE: 3,
    LOST_CHAPTER: 2,
  },
  VENIN_POISON_STACKS: 3,
  SAIGNEMENT_BLEED_STACKS: 4,
  PACTE_SANG_HP_COST: 6,
  PACTE_SANG_INK_GAIN: 3,
  FRENETIQUE_DRAW: 3,
  SEAL_BLOCK_AMOUNT: 8,
  LOST_CHAPTER_DRAW: 2,
  ENCRE_NOIRE_DAMAGE_MULTIPLIER: 2,
  VISION_DRAW: 2,

  GOLD_REWARD_BASE: 10,
  GOLD_REWARD_VARIANCE: 6,
  GOLD_PER_EXTRA_ENEMY: 5,
  ELITE_GOLD_BONUS: 18,
  BOSS_GOLD_MULTIPLIER: 2,
  RELIC_SYNERGY_BASE: 1.5,
  RELIC_SYNERGY_LUCK_BONUS: 0.3,
  RELIC_SYNERGY_MAX: 4.0,

  HEAL_ROOM_PERCENT: 0.3,
} as const;
