import { theme, type ThemeConfig } from "antd";

export const roguePalette = {
  bgBase: "#05090F",
  bgPanel: "#0A1118",
  bgElevated: "#111D2A",
  bgDisabled: "#0E141D",
  borderSubtle: "#2B3A4D",
  borderStrong: "#3A4E67",
  textPrimary: "#F6E9CF",
  textMuted: "#D0BF9F",
  textDisabled: "#6C5F4D",
  textPlaceholder: "#8B7C62",
  accentAmber: "#D9AE62",
  accentAmberHover: "#E6BF7C",
  accentAmberActive: "#B88A43",
  accentWarning: "#E2AA66",
  accentCyan: "#74C8E8",
  accentCyanHover: "#8FD5EF",
  accentCyanActive: "#56B9DF",
  accentEmerald: "#66C49A",
  accentCrimson: "#D86C6C",
  focusOutline: "rgba(116, 200, 232, 0.30)",
} as const;

export const rogueAntdTheme: ThemeConfig = {
  algorithm: theme.darkAlgorithm,
  token: {
    colorBgBase: roguePalette.bgBase,
    colorBgLayout: roguePalette.bgBase,
    colorBgContainer: roguePalette.bgPanel,
    colorBgElevated: roguePalette.bgElevated,
    colorBgContainerDisabled: roguePalette.bgDisabled,
    colorBgTextHover: "rgba(217, 174, 98, 0.12)",
    colorBgTextActive: "rgba(217, 174, 98, 0.18)",
    colorText: roguePalette.textPrimary,
    colorTextSecondary: roguePalette.textMuted,
    colorTextDisabled: roguePalette.textDisabled,
    colorTextPlaceholder: roguePalette.textPlaceholder,
    colorTextHeading: roguePalette.textPrimary,
    colorTextLabel: roguePalette.textMuted,
    colorTextDescription: roguePalette.textMuted,
    colorBorder: roguePalette.borderSubtle,
    colorBorderSecondary: roguePalette.borderStrong,
    colorSplit: "rgba(58, 78, 103, 0.45)",
    colorFillContentHover: "rgba(246, 233, 207, 0.08)",
    colorFillAlter: "rgba(255, 255, 255, 0.03)",
    colorPrimary: roguePalette.accentAmber,
    colorPrimaryHover: roguePalette.accentAmberHover,
    colorPrimaryActive: roguePalette.accentAmberActive,
    colorWarning: roguePalette.accentWarning,
    colorInfo: roguePalette.accentCyan,
    colorSuccess: roguePalette.accentEmerald,
    colorError: roguePalette.accentCrimson,
    colorLink: roguePalette.accentCyan,
    colorLinkHover: roguePalette.accentCyanHover,
    colorLinkActive: roguePalette.accentCyanActive,
    controlOutline: roguePalette.focusOutline,
    controlOutlineWidth: 2,
    lineWidthFocus: 2,
    controlItemBgHover: "rgba(246, 233, 207, 0.08)",
    controlItemBgActive: "rgba(217, 174, 98, 0.18)",
    controlItemBgActiveHover: "rgba(217, 174, 98, 0.24)",
    controlItemBgActiveDisabled: "rgba(255, 255, 255, 0.04)",
    borderRadius: 10,
    borderRadiusXS: 6,
    borderRadiusSM: 8,
    borderRadiusLG: 14,
    borderRadiusOuter: 16,
    controlHeightXS: 26,
    controlHeightSM: 34,
    controlHeight: 40,
    controlHeightLG: 46,
    fontSizeSM: 13,
    fontSize: 14,
    fontSizeLG: 16,
    fontSizeXL: 20,
    fontSizeHeading1: 36,
    fontSizeHeading2: 30,
    fontSizeHeading3: 24,
    fontSizeHeading4: 20,
    fontSizeHeading5: 16,
    lineHeightSM: 1.45,
    lineHeight: 1.5,
    lineHeightLG: 1.55,
    lineHeightHeading1: 1.2,
    lineHeightHeading2: 1.24,
    lineHeightHeading3: 1.28,
    lineHeightHeading4: 1.32,
    lineHeightHeading5: 1.36,
    fontWeightStrong: 700,
    paddingXXS: 4,
    paddingXS: 8,
    paddingSM: 12,
    padding: 16,
    paddingMD: 20,
    paddingLG: 24,
    paddingXL: 32,
    paddingContentHorizontalSM: 12,
    paddingContentHorizontal: 16,
    paddingContentHorizontalLG: 24,
    paddingContentVerticalSM: 8,
    paddingContentVertical: 12,
    paddingContentVerticalLG: 16,
    marginXXS: 4,
    marginXS: 8,
    marginSM: 12,
    margin: 16,
    marginMD: 20,
    marginLG: 24,
    marginXL: 32,
    marginXXL: 40,
    controlPaddingHorizontalSM: 8,
    controlPaddingHorizontal: 12,
    fontFamily:
      '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
  components: {
    Button: {
      fontWeight: 700,
      defaultBg: roguePalette.bgElevated,
      defaultBorderColor: roguePalette.borderSubtle,
      defaultColor: roguePalette.textPrimary,
      defaultHoverBg: "rgba(230, 191, 124, 0.08)",
      defaultHoverBorderColor: roguePalette.accentAmberHover,
      defaultHoverColor: roguePalette.textPrimary,
      defaultActiveBg: "rgba(184, 138, 67, 0.12)",
      defaultActiveBorderColor: roguePalette.accentAmberActive,
      defaultActiveColor: roguePalette.textPrimary,
      borderColorDisabled: roguePalette.borderSubtle,
      primaryColor: "#1C1408",
      primaryShadow: "0 8px 24px rgba(217, 174, 98, 0.25)",
      defaultShadow: "0 6px 16px rgba(0, 0, 0, 0.25)",
      contentFontSize: 14,
      contentFontSizeLG: 15,
      contentFontSizeSM: 13,
      contentLineHeight: 1.5,
      contentLineHeightLG: 1.5,
      contentLineHeightSM: 1.4,
      paddingInline: 14,
      paddingInlineLG: 18,
      paddingInlineSM: 10,
      paddingBlock: 6,
      paddingBlockLG: 8,
      paddingBlockSM: 4,
    },
    Tag: {
      defaultBg: "rgba(217, 174, 98, 0.12)",
      defaultColor: roguePalette.textPrimary,
    },
    Input: {
      addonBg: roguePalette.bgElevated,
      hoverBg: roguePalette.bgPanel,
      activeBg: roguePalette.bgPanel,
      hoverBorderColor: roguePalette.accentAmberHover,
      activeBorderColor: roguePalette.accentAmber,
      activeShadow: `0 0 0 2px ${roguePalette.focusOutline}`,
      errorActiveShadow: "0 0 0 2px rgba(216, 108, 108, 0.30)",
      warningActiveShadow: "0 0 0 2px rgba(226, 170, 102, 0.30)",
      paddingInline: 12,
      paddingInlineSM: 10,
      paddingInlineLG: 14,
      paddingBlock: 7,
      paddingBlockSM: 5,
      paddingBlockLG: 9,
      inputFontSize: 14,
      inputFontSizeSM: 13,
      inputFontSizeLG: 15,
    },
    Select: {
      selectorBg: roguePalette.bgPanel,
      clearBg: roguePalette.bgPanel,
      hoverBorderColor: roguePalette.accentAmberHover,
      activeBorderColor: roguePalette.accentAmber,
      activeOutlineColor: roguePalette.focusOutline,
      optionActiveBg: "rgba(246, 233, 207, 0.08)",
      optionSelectedBg: "rgba(217, 174, 98, 0.20)",
      optionSelectedColor: roguePalette.textPrimary,
      optionSelectedFontWeight: 700,
      multipleItemBg: "rgba(217, 174, 98, 0.16)",
      multipleItemBorderColor: "rgba(217, 174, 98, 0.34)",
      multipleSelectorBgDisabled: roguePalette.bgDisabled,
      multipleItemColorDisabled: roguePalette.textDisabled,
      multipleItemBorderColorDisabled: roguePalette.borderSubtle,
    },
    Tabs: {
      cardBg: roguePalette.bgElevated,
      itemColor: roguePalette.textMuted,
      itemHoverColor: roguePalette.textPrimary,
      itemActiveColor: roguePalette.accentAmberHover,
      itemSelectedColor: roguePalette.accentAmber,
      inkBarColor: roguePalette.accentAmber,
      titleFontSize: 14,
      titleFontSizeSM: 13,
      titleFontSizeLG: 15,
    },
    Segmented: {
      trackBg: roguePalette.bgElevated,
      trackPadding: 2,
      itemColor: roguePalette.textMuted,
      itemHoverColor: roguePalette.textPrimary,
      itemHoverBg: "rgba(246, 233, 207, 0.08)",
      itemActiveBg: "rgba(217, 174, 98, 0.16)",
      itemSelectedBg: "rgba(217, 174, 98, 0.24)",
      itemSelectedColor: roguePalette.textPrimary,
    },
    Modal: {
      headerBg: roguePalette.bgPanel,
      contentBg: roguePalette.bgPanel,
      footerBg: roguePalette.bgPanel,
      titleColor: roguePalette.textPrimary,
      titleFontSize: 18,
      titleLineHeight: 1.3,
    },
    Table: {
      headerBg: roguePalette.bgElevated,
      headerColor: roguePalette.textPrimary,
      borderColor: roguePalette.borderSubtle,
      rowHoverBg: "rgba(246, 233, 207, 0.05)",
      rowSelectedBg: "rgba(217, 174, 98, 0.18)",
      rowSelectedHoverBg: "rgba(217, 174, 98, 0.24)",
      cellFontSize: 14,
      cellFontSizeMD: 13,
      cellFontSizeSM: 12,
      cellPaddingInline: 14,
      cellPaddingInlineMD: 12,
      cellPaddingInlineSM: 10,
      cellPaddingBlock: 12,
      cellPaddingBlockMD: 10,
      cellPaddingBlockSM: 8,
      headerSplitColor: roguePalette.borderSubtle,
    },
    Alert: {
      defaultPadding: "10px 14px",
      withDescriptionPadding: "14px 16px",
      withDescriptionIconSize: 18,
    },
    Tooltip: {
      colorBgSpotlight: "rgba(10, 17, 24, 0.96)",
      colorTextLightSolid: roguePalette.textPrimary,
      borderRadius: 8,
    },
  },
};
